//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniqueFileGenerator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniqueFileGenerator.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cancelled..
        /// </summary>
        internal static string CancelledByUser {
            get {
                return ResourceManager.GetString("CancelledByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation aborted:.
        /// </summary>
        internal static string CancelledDueToError {
            get {
                return ResourceManager.GetString("CancelledDueToError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The character bank is empty. It must contain at least 2 characters..
        /// </summary>
        internal static string CharBankEmpty {
            get {
                return ResourceManager.GetString("CharBankEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The character bank must contain at least 2 characters..
        /// </summary>
        internal static string CharBankTooShort {
            get {
                return ResourceManager.GetString("CharBankTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 file created..
        /// </summary>
        internal static string CompletedOne {
            get {
                return ResourceManager.GetString("CompletedOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files created..
        /// </summary>
        internal static string CompletedZeroOrMultiple {
            get {
                return ResourceManager.GetString("CompletedZeroOrMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve requested a lot of files. Continue?.
        /// </summary>
        internal static string CountWarning {
            get {
                return ResourceManager.GetString("CountWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve requested a very long delay between files. Continue?.
        /// </summary>
        internal static string DelayWarning {
            get {
                return ResourceManager.GetString("DelayWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred when reading the drive information..
        /// </summary>
        internal static string DriveInfoReadError {
            get {
                return ResourceManager.GetString("DriveInfoReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough free space on this disk to continue..
        /// </summary>
        internal static string DriveSpaceInsufficient {
            get {
                return ResourceManager.GetString("DriveSpaceInsufficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File content must be specified..
        /// </summary>
        internal static string FileContentInvalid {
            get {
                return ResourceManager.GetString("FileContentInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a file count of at least 1 as the first argument..
        /// </summary>
        internal static string FileCountInvalidRange {
            get {
                return ResourceManager.GetString("FileCountInvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file count cannot be zero..
        /// </summary>
        internal static string FileCountInvalidZero {
            get {
                return ResourceManager.GetString("FileCountInvalidZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file count must be specified..
        /// </summary>
        internal static string FileCountMissing {
            get {
                return ResourceManager.GetString("FileCountMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a file count between 1 and 4,294,967,295 (inclusive) as the first argument..
        /// </summary>
        internal static string FileCountTooHigh {
            get {
                return ResourceManager.GetString("FileCountTooHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file creation delay must be 0 or higher..
        /// </summary>
        internal static string FileCreationDelayOutOfRange {
            get {
                return ResourceManager.GetString("FileCreationDelayOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid filename was specified..
        /// </summary>
        internal static string FileNameInvalid {
            get {
                return ResourceManager.GetString("FileNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file size must be a positive number greater than 0..
        /// </summary>
        internal static string FileSizeInvalidRange {
            get {
                return ResourceManager.GetString("FileSizeInvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size cannot be 0..
        /// </summary>
        internal static string FileSizeInvalidZero {
            get {
                return ResourceManager.GetString("FileSizeInvalidZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A flag can only be specified once..
        /// </summary>
        internal static string FlagCanBeUsedOnce {
            get {
                return ResourceManager.GetString("FlagCanBeUsedOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length cannot be negative..
        /// </summary>
        internal static string LengthInvalidNegative {
            get {
                return ResourceManager.GetString("LengthInvalidNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This drive&apos;s path root could not be determined..
        /// </summary>
        internal static string PathRootParseError {
            get {
                return ResourceManager.GetString("PathRootParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve requested very large files. Continue?.
        /// </summary>
        internal static string SizeWarning {
            get {
                return ResourceManager.GetString("SizeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The count of desired strings must be greater than zero..
        /// </summary>
        internal static string StringCountZero {
            get {
                return ResourceManager.GetString("StringCountZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of each string must be greater than zero..
        /// </summary>
        internal static string StringLengthZero {
            get {
                return ResourceManager.GetString("StringLengthZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A flag was not specified for &quot;{0}&quot;..
        /// </summary>
        internal static string ValueWithNoFlag {
            get {
                return ResourceManager.GetString("ValueWithNoFlag", resourceCulture);
            }
        }
    }
}
